version: '2'

services:
  app:
    image: 'sensor-api:latest'
    ports: 
      - '8080:8080'
    build:
      context: .
    container_name: app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:15.2-alpine3.17'
    restart: always
    container_name: db
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5
